name: Trigger Target Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        env:
          REPO_OWNER: "ssaczkowski"
          REPO_NAME: "prueba-workflows-repo2"
          EVENT_TYPE: "trigger-workflow"
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/dispatches \
            -d "{\"event_type\": \"$EVENT_TYPE\", \"client_payload\": {\"unit\": false, \"integration\": true}}"
